[features]
seeds = false
skip-lint = false
[programs.devnet]
storage_program_1 = "BJvFZwdNnCLmBUAGmDwL5Yy4pgwXMCxtZ3ScDQmm2vP4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nataliiabalashova/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
